### ISSUE TITLE
User can search for anime by name

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/ajax-project#1]
## 💰 Motivation

Anime enthusiasts will want to look for anime they want to watch.

## 📐 Plan

Create a search bar to search for an anime by its name.

## 🖼️ Wireframes

![user can delete an entry mobile](https://user-images.githubusercontent.com/6316645/147998237-3fd557f3-1bd0-4767-b01b-c5d4983f44e6.png)
![user can delete an entry desktop](https://user-images.githubusercontent.com/6316645/147998239-b5acb5e3-ef28-4694-89b1-48e15bcfb349.png)

## ✅ Task List

- [x] Add a div `[data-view="search-form"]` to the HTML
- [x] Add anime title search bar to div `[data-view="search-form"]`
- [x] Put logo above search bar
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
