### ISSUE TITLE
User can see search results

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/ajax-project#2]
## 💰 Motivation

Users will want to see a list of results of the anime title they typed in the search bar.

## 📐 Plan

Display list of search results for the user to look through and to read about.

## 🖼️ Wireframes

![search-results mobile](https://user-images.githubusercontent.com/6316645/148141861-9e8c1a4c-c616-4a6f-8501-f7315d96b341.png)

![search-results desktop 1](https://user-images.githubusercontent.com/6316645/148142729-031dcf17-1c87-4f53-8a9c-c990a8e6671d.jpg)

![search-results desktop 2](https://user-images.githubusercontent.com/6316645/148142744-dd63c147-748f-43b6-b3ca-4a1c4a66f5c4.jpg)

## ✅ Task List

- [x] Add a div `[data-view="search-results"]`.
- [x] Make a dummy anime search result that looks identical to the wireframe.
- [x] Make a `<ul>` element for appending search results.
- [x] Create a function that generates a DOM Tree for information for search results.
- [x]  Append those DOM Trees to the `<ul>`.
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
