### ISSUE TITLE
User can view an anime's information

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/ajax-project#3]
## 💰 Motivation

Users should be able to view additional information about the anime title they clicked on from the list of search results.

## 📐 Plan

Allow users to view detailed information such as genres and a brief synopsis of the selected anime title.

## 🖼️ Wireframes

![view-anime-info mobile](https://user-images.githubusercontent.com/6316645/148435843-64360bcf-a3c3-4127-837a-54577c019fbf.png)

![view-anime-info desktop](https://user-images.githubusercontent.com/6316645/148435840-933ab414-3a01-45be-a2eb-d487e5f4f947.png)

## ✅ Task List

- [x] Create a div with `[data-view="anime-info"]`.
- [x] Query the DOM for all anime titles in search result list.
- [x] Make a dummy anime information page that looks identical to the wireframe.
- [x] Create a DOM tree for anime information.
- [x] Give anime titles in search result list an attribute of `"anime-id"`
- [x] Use HTTP `GET` to make a request for the anime title clicked.
- [x] Fill in necessary anime information in the DOM tree.
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
