### ISSUE TITLE
User can add anime to watch list

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/ajax-project#4]
## 💰 Motivation

Users will want to have a place to keep track of their anime.

## 📐 Plan

Allow users to add anime to their watch list from an anime's detailed information page.

## 🖼️ Wireframes

![add-to-watchlist mobile](https://user-images.githubusercontent.com/6316645/148589609-014e2265-bd5b-4d88-a8a2-7c7f09e8d049.png)
![add-to-watchlist desktop](https://user-images.githubusercontent.com/6316645/148589646-5198aea1-c502-461c-9abb-26e6d83429bb.png)

## ✅ Task List

- [x] Add a div `[data-view="watch-list"]` to the HTML.
- [x] Put a "+ Add to List" button in the detailed anime information page.
- [x] Include a watch list button on the navigation bar.
- [x] Add a `watchlist` property to the data model.
- [x] Make a dummy watch list entry that looks identical to the wireframe.
- [x] Create a DOM tree for watch list entry information.
- [x] Add a `<ul>`  to append watch list entries.
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
