### ISSUE TITLE
User can remove anime from watch list

### ISSUE THREAD

**Issue by meganbmartinez** [meganbmartinez/ajax-project#5]
## 💰 Motivation

User should have a choice on whether they want to keep certain anime titles on their list.

## 📐 Plan

Allow user to remove anime entries from watch list.

## 🖼️ Wireframes

![delete-an-anime mobile](https://user-images.githubusercontent.com/6316645/148892778-6e6d2e68-97b3-4d48-8daa-89e8c16379a0.png)
![delete-an-anime desktop](https://user-images.githubusercontent.com/6316645/148892781-5f4bacb3-6e5c-44fe-b238-7c4117077d48.png)

## ✅ Task List

- [x] Create and append a delete button to the watch list DOM tree.
- [x] Add `watchlist-id` as a class for start of watch list DOM tree.
- [x] Delete watch list entry if its watch list's watchlist-id is the same as the data model's.
- [x] Put a confirmation modal to make sure user really wants to delete anime entry.
- [x] Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
